---
# Copyleft (c) 2021 Contributors to Smart Data Models initiative
# 


components:
  schemas: 
    PhotovoltaicMeasurement: 
      $ref: "https://smart-data-models.github.io/dataModel.GreenEnergy/PhotovoltaicMeasurement/model.yaml#/PhotovoltaicMeasurement"
info:
  description:  |
    The Data Model is intended to measure the continuous power transferred by the photo-voltaic panel to an Inverter Device.
  title: PhotovoltaicMeasurement
  version: "1.0.0"
openapi: "3.0.0"

paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - PhotovoltaicMeasurement
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.GreenEnergy/PhotovoltaicMeasurement/examples/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.GreenEnergy/PhotovoltaicMeasurement/examples/example-normalized.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
